### ISSUE TITLE
Inventory and Possessions -- A Collection

### ISSUE THREAD

**Issue by Medsmiley** [elyukai/optolith-client#1121]
This issue is supposed to bring every feature wish regarding the inventory to one place.

## Money
- [ ] Char creation: transfer left money automatically into pockets #62 
- [ ] Show total price after hero creation #505 #844
- [ ] Display single item cost #844 #1095
- [ ] Sort equipment by cost #1095

## Weight
- [ ] Option to not include items in total weight #60 
- [ ] Warn if equipment is too heavy #304
- [ ] Single unit for weights  #843

## Amount
- [ ] Entering amount when addings items #764 -> related to following
- [ ] Proposal for new way of adding and maintain the amount of items  #1119

## Sets / Packages
- [ ] Single entries containing more than 1 item: field to keep track of how many left  #765 -> related to following 
- [ ] 

- [ ] Create armor and weapon sets -> calculation of all the final values (PRO, ENC, etc). #59 
- [ ] Equipment packs to add multiple items at once #73 #208 
- [ ] Custom packs creatable and saved locally, available for all chars #207 

## Armor
- [ ] Hit Zone Armor creation: show PRO #47 

### Weapons
- [ ] Multiple use cases (weapons) in a single item #87 
- [ ] Show material a weapon consists of #303 #745 
- [ ] Display Two-Handed and Improvised for weapons #535

### Items
- [ ] Multiple levels for potions #63 
- [ ] Magical Artifacts/Weapons incl. their special properties #408 #745 
- [ ] More information for specific types of items (herbs, elixirs, …) #842

### Processes
- [ ] copy-paste (or relocate) items between chars #206 
- [ ] Custom items: sort equipment groups alphabetically #545
- [ ] Notes and rules of an item should be editable  #714
- [ ] Apply or show rules/effects of items #744

# Inventory
Additional points to the ones above.
- [ ] Show "carry location" in list #709

# Shop
Additional points to the ones above.
- [ ] replace drop down list for better UX #72 
- [ ] Highlight ordinary/recommended items for race, culture, profession, ... #234 
- [ ] Show total money and money spent while in shop #265 

# Char Sheet PDF
- [ ] Sort options for equipment on character sheet #643
