### ISSUE TITLE
AMA2: Special Abilities

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#116]
### Sources

**Hinweis:** Alle Listen außer den Kulturen und Professionen müssen vorher fertig sein.

* S. 15-18 (Gildenmagische Magierkugel)
* S. 26-29 (Kesselzauber)
* S. 30 (Tradition Schelme)
* S. 35-37 (Narrenkappe)
* S. 38-39 (Schelmenspielzeug)
* S. 40 (Tradition Zauberalchimisten)
* S. 41-43 (Schalenzauber)
* S. 52 (Berufsgeheimnis Kraftlinien und -knoten)
* S. 70-84 (Allgemeine Sonderfertigkeiten, Zauberstile und Erweiterte Sonderfertigkeiten)

### Tables

- [x] Univ
- [x] L10n de-DE
- [x] Gebräu bei Kesselzauber aufnehmen

### Code

- [x] Scholar der Akademie des Magischen Wissens zu Methumis Seite 74 eine erweiterte Zaubersonderfertigkeit aus einem Nebenfach (siehe Kasten.) #347 
- [x] Kraftliniennutzung S.72, Voraussetzung: Tradition muss Rituale einsetzen können #348
- [x] Besonderheiten der Tradition (Schelme) #349
- [x] Besonderheiten der Tradition (Zauberalchimisten) #350
- [x] Effekt Große Meditation
- [x] Effekt Imitationszauberei #417
- [x] Effekt Scholar der Halle des Lebens zu Norburg
- [x] Effekt Scholar des Kreises der Einfühlung
- [x] Effekt Madaschwestern #351
- [x] Scholar des Magierkollegs zu Honingen: Erweiterte Sonderfertigkeiten #418
