### ISSUE TITLE
Missing Rule Books

### ISSUE THREAD

**Issue by elyukai** [elyukai/optolith-client#71]
### German
- [ ] Aventurische Magie II #41 
- [ ] Aventurische Magie III #92 
- [ ] Aventurische Rüstkammer II
- [ ] Aventurisches Bestiarium II
- [ ] Aventurisches Kompendium II #93 
- [ ] Havena &ndash; Versunkene Geheimnisse
  - [ ] Unendlichkeit & Tiefenrausch
- [ ] Wege der Vereinigungen
  - [ ] Lustschlösser & Zauberwesen
- [ ] Flusslande &ndash; Kosch & Nordmarken
  - [ ] Rüstkammer der Flusslande

### English
- [x] Aventuria Compendium I
- [x] Aventuria Bestiary I
- [x] The Warring Kingdoms
  - [x] Armory of The Warring Kingdoms
- [x] Inns & Taverns
- [x] Magic of Aventuria

### Dutch
- [x] Core Rules
- [ ] Aventuria Almanach
